### ISSUE TITLE
Windows Update shutdown icon

### ISSUE THREAD

**Issue by NuraliMedeu** [bonzibudd/Fluent-Metro#106]
## Description
The icon inside the modern (minimalistic) shutdown button gets misaligned during Windows Update.

## Expected behavior
A properly aligned update icon appears inside the modern shutdown button.

## Screenshots
Sorry, I didn't make screenshots when I noticed this issue because I was unsure whether I need to report it.

## Version:
 - Windows 10 Pro 20H2
 - Fluent-Metro: v1.3

**Comment by bonzibudd** [comment]
It should be mostly fixed in 1.3.1 and 1.4. However, if you see the issue again after installing the new version, it's probably a DPI related problem, which I should be able to fix. I'll close this for now, but we can re-open if the problem comes back.

**Comment by NuraliMedeu** [comment]
Thank you for the quick response! For more clarity, I have been using Fluent-Metro in 135 DPI for a few weeks and I've already switched to v1.4 yesterday.

**Comment by bonzibudd** [comment]
Ok, it does make sense that the icon may not be properly aligned at that DPI. I made some changes to make it so that the icons should stay aligned better.

One downside of this is that the button will end up being a few pixels smaller at that size, however it shouldn’t be much of an issue. I’ll push out a testing release sometime soon and you can see if you notice a difference.

**Comment by bonzibudd** [comment]
I just released [1.4.1](https://github.com/bonzibudd/Fluent-Metro/releases/tag/v1.4.1), and it adds some changes which should improve the placement when updating. If you see the problem come back after updating, please let me know.

**Comment by NuraliMedeu** [comment]
Thank you, I will try it some time later. :)

**Comment by bonzibudd** [comment]
I'm closing this for now, it can be re-opened if the issue shows up again.

**Comment by NuraliMedeu** [comment]
Hi! I'm sorry for disturbing you again. The issue is still present:

![image](https://user-images.githubusercontent.com/44456615/121776824-cc778680-cbb0-11eb-93cf-692e6b156c7b.png)

**Comment by bonzibudd** [comment]
Interesting. This looks like an uncommon layout, and the button is getting cut off on the right side. I will try to improve this in the future, but for now, try disabling the "Thinner right-hand width" option.

Let me know if this makes a difference.

**Comment by bonzibudd** [comment]
I made some more changes in 1.5.1 which should adjust for the extra space. Let me know if that makes a difference.

**Comment by NuraliMedeu** [comment]
Hello! Sorry for not writing back for a long time. I found a different solution to this issue, so I am closing it.
